name: michaelhaslimphotography
favicon: null
layout_spectrum: 0.38882712670601904
typography_spectrum: 0.18179804598912597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.015804006718099117
  lightness: 0.6333881227765232
  saturation: 0.7036971522029489
  rhythmicContrast: 0.6962125462014228
purpose: []
